### ISSUE TITLE
Add FAQ Section to Homepage

### ISSUE THREAD

**Issue by Supermathew** [GDSC-FCRIT/website#1]
I'd like to propose adding a FAQ (Frequently Asked Questions) section to the homepage of our website. This will help Students find answers to common questions quickly and improve user experience.

## Implementation Details
- We should create a dedicated FAQ page or section on the homepage.
- FAQs should be well-structured and easy to navigate.
- Content should be easy to update, preferably using a Accordion Style Format.
- Consideration for mobile responsiveness is important.

## Additional Notes
Please feel free to share your ideas and suggestions on how we can best implement this feature.

![faq](https://github.com/GDSC-FCRIT/website/assets/84656423/d9bb81d9-93c7-4066-a890-41fcb43a41a1)

- For mockup refer this image. 
- You can use summary tag to implement this.
- You will find the Faq component( /component/Faq.js ) in the component folder.

**Comment by rituraj12797** [comment]
@Supermathew 
please assign this issue to me also i want to work on this issue .

**Comment by karishmarajput** [comment]
![faq](https://github.com/GDSC-FCRIT/website/assets/84656423/d9bb81d9-93c7-4066-a890-41fcb43a41a1)
For mockup refer this image. You can use summary tag to implement this.
You will find the Faq component( /component/Faq.js ) in the component folder.

**Comment by Savio629** [comment]
Updates @rituraj12797 ?

**Comment by rituraj12797** [comment]
sir this is in react i wont be able to do it as of now

**Comment by Savio629** [comment]
No worries. Thanks for letting us know👍

**Comment by dalvishruti14** [comment]
Please assign this issue to me. I would like to work.
