### ISSUE TITLE
Convert Vanilla CSS to TailwindCSS

### ISSUE THREAD

**Issue by Arjun-Praveen-Varshney** [GDSC-FCRIT/website#12]
Changing the css configuration in the project setup will help in a lot of ways. Firstly, the work of the developers will become less tedious because everything will be in the same file; instead of 2 files (one for the code and the other for css styling). Secondly, it will be more readable and easily understandable. Moreover, the codebase can be maintained on a long-term basis by doing so. Lastly, it would be easier to contribute on once people get familiar with the meaningfulness of the class names used in tailwindcss. For example, we can write class="div1" and then apply all the css styles in it...But there's a problem; we have to switch back-and-forth between the .css file and the react component file. By using tailwindcss, this problem is solved as we can write meaningful names like class="m-4" which means the same as `.m-4 {margin: 4rem;}`.

**Comment by ProfoundlyParker** [comment]
Hi there, I'd like to work on this task, can you assign me, please? Thanks! 👍🏻

**Comment by kunal-511** [comment]
Please assign me this task I am working on tailwindCss and I will be happy work on this.

**Comment by ProfoundlyParker** [comment]
Hi, @kunal-511. I submitted a pull request with the Tailwind CSS changes yesterday, pending approval, so this issue is already being taken care of. Best of luck 🤞🏻

**Comment by karishmarajput** [comment]
completed
