### ISSUE TITLE
Fix: Make navbar mobile responsive

### ISSUE THREAD

**Issue by akash0708** [GDSC-FCRIT/website#17]
### Current navbar
![image](https://github.com/GDSC-FCRIT/website/assets/110753356/6d1225a3-9f84-464b-b76c-4697b10e180c)

### Fix:
The nav elements will appear only on clicking on the hamburger icon

**Comment by Rahul-Roy-Hub** [comment]
Plz Assign to me I will work on that.

**Comment by Savio629** [comment]
As @akash0708 has opened this issue, let him solve this issue...

**Comment by akash0708** [comment]
@Savio629 , I have started working on it. Can you please add the hacktoberfest-accepted label?

**Comment by akash0708** [comment]
And can I use Tailwind css in the project ? @Savio629

**Comment by Savio629** [comment]
Yes @akash0708

**Comment by DarrenDsouza7273** [comment]
hi @akash0708 can u update regarding your progress on this issue

**Comment by akash0708** [comment]
Hello @DarrenDsouza7273 , I am not working on this issue anymore since @Rahul-Roy-Hub has taken over this issue. You can check PR #31 to get a better understanding of what I'm trying to say.

**Comment by Rahul-Roy-Hub** [comment]
@DarrenDsouza7273 Check the PR #31

**Comment by veerendra19codes** [comment]
Is this issue still open,can you assign this to me?
