### ISSUE TITLE
Spelling Mistake on the Landing Page 

### ISSUE THREAD

**Issue by DarrenDsouza7273** [GDSC-FCRIT/website#21]
There is a spelling mistake on the Home/landing page
-
The spelling of Rodriguez needs to be changed to Rodrigues

**Comment by DarrenDsouza7273** [comment]
https://drive.google.com/file/d/132p3SEbJmlDHrbQRpOqJGtzuQ9VA09TQ/view?usp=drive_link

**Comment by kelumsri** [comment]
Can you assign this issue to me ?
