### ISSUE TITLE
Change navbar logo

### ISSUE THREAD

**Issue by karishmarajput** [GDSC-FCRIT/website#3]
Update the navbar logo to image provided. Make sure it looks good and is responsive for mobile as well.
For mobile you can use the existing logo but for the laptop devices update the logo.

![mainLogo](https://github.com/GDSC-FCRIT/website/assets/84656423/6752bb1a-e03a-433e-813b-d4aac312bcb9)

**Comment by Panth1823** [comment]
Hey @karishmarajput i would like to work on this issue
