### ISSUE TITLE
Fix grammatical mistakes

### ISSUE THREAD

**Issue by chengm405** [GDSC-FCRIT/website#32]
There are numerous grammatical mistakes & clarity issues in the program. 
Please assign the issue to me.

**Comment by chengm405** [comment]
![image](https://github.com/GDSC-FCRIT/website/assets/146371159/d6a9aafd-74b9-48a1-be60-a4f63608ba4e)
GDSC, although Clubs is plural, when it is an acronym, it becomes singular so hosts would be grammatically correct
![image](https://github.com/GDSC-FCRIT/website/assets/146371159/b4e39c47-5201-4b39-a728-e9849433f114)
Extra r after everyone, if this is intentional then it may be unclear to people reading
![image](https://github.com/GDSC-FCRIT/website/assets/146371159/619bdfbb-0a90-467c-ac05-298945ce1412)
Learnings is less common in use so switching with a more common word such as knowledge for more clarity could work
![image](https://github.com/GDSC-FCRIT/website/assets/146371159/8d3f244c-6752-4651-958c-9b88558817bd)
Some better clarity by specifying the online and in-person could be clearer, but doesn't need to change

here's some screenshots about things I found

**Comment by DarrenDsouza7273** [comment]
@Savio629
