### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by Shaurya10101** [GDSC-FCRIT/website#33]
I want to add information about GDSC ( aim , vision , perks ) , Guidelines of Contribution , Code of Conduct and contributors 
Please assign me this issue under Hacktoberfest

**Comment by Shaurya10101** [comment]
Aim : State the project's purpose and vision or goals . Explain about gdsc 

Perks for Contributors: Benefits and rewards contributors can expect, such as skill development, networking or recognition. What will they get when they join gdsc

Guidelines of Contribution: Outline contribution guidelines, including how to fork, clone, branch, and submit pull requests.

Code of Conduct: Include a section with  clear code of conduct that contributors must adhere to. Creating a respectful environment 

Contributors: adding a section that lists contributors ( names, GitHub profiles)

**Comment by Shaurya10101** [comment]
@DarrenDsouza7273

**Comment by Savio629** [comment]
I don't think we need these changes right now...
