### ISSUE TITLE
Typo under "Our Community Guidelines"

### ISSUE THREAD

**Issue by RahulDeoghare** [GDSC-FCRIT/website#36]
"experience for everyone r regardless"
It should be "experience for everyone regardless"
![image](https://github.com/GDSC-FCRIT/website/assets/97783104/bbd8fe2d-61aa-43f9-8953-02a3c3754c0d)

**Comment by DarrenDsouza7273** [comment]
Lets assign it to someone else @RahulDeoghare please check out other available issues

**Comment by veerendra19codes** [comment]
@Savio629 please review my PR ,thank you for assigning me✌️🙌

**Comment by veerendra19codes** [comment]
Hey @Savio629 if there are no improvements in my PR and if you satisfied with my chances,can you merge it😅😅

**Comment by veerendra19codes** [comment]
Thank you for merging,cheers🥳🙌
