### ISSUE TITLE
Navbar links not working 

### ISSUE THREAD

**Issue by harshitkandpal** [GDSC-FCRIT/website#38]
I have tried to navigate through navbar links but it turned out it's not working .
I would like to work on this issue ![Screenshot_2023-10-18-08-36-03-471_com.android.chrome-edit.jpg](https://github.com/GDSC-FCRIT/website/assets/111063866/ccaddea0-64be-4eda-a07c-6f4d50d72181)

**Comment by parthasawa100** [comment]
Please assign the Task to me so I can push the updated code

**Comment by harshitkandpal** [comment]
Thanks I will do it in 1-2 days
