### ISSUE TITLE
Update README for npm and Yarn Support

### ISSUE THREAD

**Issue by karishmarajput** [GDSC-FCRIT/website#4]
Currently, the README.md file provides instructions for cloning, installing, and running the project using npm. To make our project more accessible to a wider audience, we should update the README to include instructions for both npm and Yarn.

Additional Information:

1. Consider revising the wording to make the instructions more user-friendly.
2. Ensure that all necessary prerequisites are mentioned in the README.
3. Verify that the instructions are accurate and up-to-date.

**Comment by aecuto** [comment]
please assign me

**Comment by itsankitbhusal** [comment]
I will be working on this issue, can you assign it to me?

**Comment by itsankitbhusal** [comment]
@karishmarajput readme enhancement pull request is opened

**Comment by itsankitbhusal** [comment]
@karishmarajput please have a look on my new pull request #14
