### ISSUE TITLE
GDSC logo not visible on phone 

### ISSUE THREAD

**Issue by harshitkandpal** [GDSC-FCRIT/website#49]
![Screenshot 2023-10-27 220043](https://github.com/GDSC-FCRIT/website/assets/111063866/18925550-3959-4e45-9223-43fbff4e39e5)

We can have this logo their to navigate into the \ route 
![Screenshot 2023-10-27 220020](https://github.com/GDSC-FCRIT/website/assets/111063866/eb741151-b164-4294-a5fe-7eb7378f9156)

**Comment by harshitkandpal** [comment]
https://github.com/GDSC-FCRIT/website/assets/111063866/910e3d93-9e0c-411b-b688-59352fe58a46

once you merge my previous pull request i will make a new pull request for this feature

**Comment by Savio629** [comment]
You can go ahead
