### ISSUE TITLE
Update Title to "GDSC FCRIT" and Favicon

### ISSUE THREAD

**Issue by karishmarajput** [GDSC-FCRIT/website#6]
We need to update the project title to "GDSC FCRIT" and replace the current favicon with the provided image.

Additional Information:

- Make sure the provided favicon image meets the required dimensions and format.
- Test the changes to ensure that the new title and favicon are displayed correctly in web browsers.

**Comment by bishwobista** [comment]
where is the provided image?

**Comment by devmusiczz** [comment]
hey @karishmarajput I can work on this. Can you please assign this issue to me?
