### ISSUE TITLE
Make the navbar stick at the top.

### ISSUE THREAD

**Issue by devmusiczz** [GDSC-FCRIT/website#9]
Currently, the navbar is also scrolled up when we scroll the website. We can use a sticky navbar at the top it helps visitors quickly access the content they seek. Users may obtain the material they require without always having to scroll to the top of the page by having the sticky navigation menu permanently displayed.

**Comment by devmusiczz** [comment]
hey @karishmarajput @Savio629 Can you assign this issue to me? and add the suitable labels also.

**Comment by Arjun-Praveen-Varshney** [comment]
In the navbar component, search this line in the code: 
<AppBar position="static" className="navbarDiv">
and change the position attribute from static to "fixed"...this solves the issue

**Comment by Arjun-Praveen-Varshney** [comment]
In the navbar component, search this line in the code:
`<AppBar position="static" className="navbarDiv">`
now, change the value of the position attribute from static to "fixed"...this solves the issue

**Comment by karishmarajput** [comment]
Issue solved
